Event Bug Found Trying To Find A Fix
System.InvalidCastException: Unable to cast COM object of type
'System.__ComObject' to interface type
'BMDSwitcherAPI.IBMDSwitcherMixEffectBlock'. This operation failed
because the QueryInterface call on the COM component for the interface
with IID '{11974D55-45E0-49D8-AE06-EEF4D5F81DF6}'  Trying to find a fix